// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessageFormat.proto

package com.POD.iiit;

public final class MessageUnit {
  private MessageUnit() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ClockNDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ClockNData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>required int32 id = 1;</code>
     */
    int getId();

    /**
     * <code>required string msgLine = 2;</code>
     */
    boolean hasMsgLine();
    /**
     * <code>required string msgLine = 2;</code>
     */
    java.lang.String getMsgLine();
    /**
     * <code>required string msgLine = 2;</code>
     */
    com.google.protobuf.ByteString
        getMsgLineBytes();

    /**
     * <code>repeated int32 clock = 3;</code>
     */
    java.util.List<java.lang.Integer> getClockList();
    /**
     * <code>repeated int32 clock = 3;</code>
     */
    int getClockCount();
    /**
     * <code>repeated int32 clock = 3;</code>
     */
    int getClock(int index);
  }
  /**
   * Protobuf type {@code ClockNData}
   */
  public  static final class ClockNData extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:ClockNData)
      ClockNDataOrBuilder {
    // Use ClockNData.newBuilder() to construct.
    private ClockNData(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private ClockNData() {
      id_ = 0;
      msgLine_ = "";
      clock_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ClockNData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt32();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              msgLine_ = bs;
              break;
            }
            case 24: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                clock_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000004;
              }
              clock_.add(input.readInt32());
              break;
            }
            case 26: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004) && input.getBytesUntilLimit() > 0) {
                clock_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000004;
              }
              while (input.getBytesUntilLimit() > 0) {
                clock_.add(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          clock_ = java.util.Collections.unmodifiableList(clock_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.POD.iiit.MessageUnit.internal_static_ClockNData_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.POD.iiit.MessageUnit.internal_static_ClockNData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.POD.iiit.MessageUnit.ClockNData.class, com.POD.iiit.MessageUnit.ClockNData.Builder.class);
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>required int32 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int MSGLINE_FIELD_NUMBER = 2;
    private volatile java.lang.Object msgLine_;
    /**
     * <code>required string msgLine = 2;</code>
     */
    public boolean hasMsgLine() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string msgLine = 2;</code>
     */
    public java.lang.String getMsgLine() {
      java.lang.Object ref = msgLine_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          msgLine_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string msgLine = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMsgLineBytes() {
      java.lang.Object ref = msgLine_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msgLine_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CLOCK_FIELD_NUMBER = 3;
    private java.util.List<java.lang.Integer> clock_;
    /**
     * <code>repeated int32 clock = 3;</code>
     */
    public java.util.List<java.lang.Integer>
        getClockList() {
      return clock_;
    }
    /**
     * <code>repeated int32 clock = 3;</code>
     */
    public int getClockCount() {
      return clock_.size();
    }
    /**
     * <code>repeated int32 clock = 3;</code>
     */
    public int getClock(int index) {
      return clock_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMsgLine()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, msgLine_);
      }
      for (int i = 0; i < clock_.size(); i++) {
        output.writeInt32(3, clock_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, msgLine_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < clock_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(clock_.get(i));
        }
        size += dataSize;
        size += 1 * getClockList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static com.POD.iiit.MessageUnit.ClockNData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.POD.iiit.MessageUnit.ClockNData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.POD.iiit.MessageUnit.ClockNData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.POD.iiit.MessageUnit.ClockNData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.POD.iiit.MessageUnit.ClockNData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.POD.iiit.MessageUnit.ClockNData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.POD.iiit.MessageUnit.ClockNData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.POD.iiit.MessageUnit.ClockNData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.POD.iiit.MessageUnit.ClockNData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.POD.iiit.MessageUnit.ClockNData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.POD.iiit.MessageUnit.ClockNData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ClockNData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ClockNData)
        com.POD.iiit.MessageUnit.ClockNDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.POD.iiit.MessageUnit.internal_static_ClockNData_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.POD.iiit.MessageUnit.internal_static_ClockNData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.POD.iiit.MessageUnit.ClockNData.class, com.POD.iiit.MessageUnit.ClockNData.Builder.class);
      }

      // Construct using com.POD.iiit.MessageUnit.ClockNData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        msgLine_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        clock_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.POD.iiit.MessageUnit.internal_static_ClockNData_descriptor;
      }

      public com.POD.iiit.MessageUnit.ClockNData getDefaultInstanceForType() {
        return com.POD.iiit.MessageUnit.ClockNData.getDefaultInstance();
      }

      public com.POD.iiit.MessageUnit.ClockNData build() {
        com.POD.iiit.MessageUnit.ClockNData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.POD.iiit.MessageUnit.ClockNData buildPartial() {
        com.POD.iiit.MessageUnit.ClockNData result = new com.POD.iiit.MessageUnit.ClockNData(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.msgLine_ = msgLine_;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          clock_ = java.util.Collections.unmodifiableList(clock_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.clock_ = clock_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.POD.iiit.MessageUnit.ClockNData) {
          return mergeFrom((com.POD.iiit.MessageUnit.ClockNData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.POD.iiit.MessageUnit.ClockNData other) {
        if (other == com.POD.iiit.MessageUnit.ClockNData.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasMsgLine()) {
          bitField0_ |= 0x00000002;
          msgLine_ = other.msgLine_;
          onChanged();
        }
        if (!other.clock_.isEmpty()) {
          if (clock_.isEmpty()) {
            clock_ = other.clock_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureClockIsMutable();
            clock_.addAll(other.clock_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          return false;
        }
        if (!hasMsgLine()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.POD.iiit.MessageUnit.ClockNData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.POD.iiit.MessageUnit.ClockNData) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>required int32 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object msgLine_ = "";
      /**
       * <code>required string msgLine = 2;</code>
       */
      public boolean hasMsgLine() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string msgLine = 2;</code>
       */
      public java.lang.String getMsgLine() {
        java.lang.Object ref = msgLine_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            msgLine_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string msgLine = 2;</code>
       */
      public com.google.protobuf.ByteString
          getMsgLineBytes() {
        java.lang.Object ref = msgLine_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          msgLine_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string msgLine = 2;</code>
       */
      public Builder setMsgLine(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        msgLine_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string msgLine = 2;</code>
       */
      public Builder clearMsgLine() {
        bitField0_ = (bitField0_ & ~0x00000002);
        msgLine_ = getDefaultInstance().getMsgLine();
        onChanged();
        return this;
      }
      /**
       * <code>required string msgLine = 2;</code>
       */
      public Builder setMsgLineBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        msgLine_ = value;
        onChanged();
        return this;
      }

      private java.util.List<java.lang.Integer> clock_ = java.util.Collections.emptyList();
      private void ensureClockIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          clock_ = new java.util.ArrayList<java.lang.Integer>(clock_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <code>repeated int32 clock = 3;</code>
       */
      public java.util.List<java.lang.Integer>
          getClockList() {
        return java.util.Collections.unmodifiableList(clock_);
      }
      /**
       * <code>repeated int32 clock = 3;</code>
       */
      public int getClockCount() {
        return clock_.size();
      }
      /**
       * <code>repeated int32 clock = 3;</code>
       */
      public int getClock(int index) {
        return clock_.get(index);
      }
      /**
       * <code>repeated int32 clock = 3;</code>
       */
      public Builder setClock(
          int index, int value) {
        ensureClockIsMutable();
        clock_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 clock = 3;</code>
       */
      public Builder addClock(int value) {
        ensureClockIsMutable();
        clock_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 clock = 3;</code>
       */
      public Builder addAllClock(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureClockIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, clock_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 clock = 3;</code>
       */
      public Builder clearClock() {
        clock_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ClockNData)
    }

    // @@protoc_insertion_point(class_scope:ClockNData)
    private static final com.POD.iiit.MessageUnit.ClockNData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.POD.iiit.MessageUnit.ClockNData();
    }

    public static com.POD.iiit.MessageUnit.ClockNData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<ClockNData>
        PARSER = new com.google.protobuf.AbstractParser<ClockNData>() {
      public ClockNData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new ClockNData(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<ClockNData> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ClockNData> getParserForType() {
      return PARSER;
    }

    public com.POD.iiit.MessageUnit.ClockNData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ClockNData_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ClockNData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023MessageFormat.proto\"8\n\nClockNData\022\n\n\002i" +
      "d\030\001 \002(\005\022\017\n\007msgLine\030\002 \002(\t\022\r\n\005clock\030\003 \003(\005B" +
      "\033\n\014com.POD.iiitB\013MessageUnit"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_ClockNData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ClockNData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ClockNData_descriptor,
        new java.lang.String[] { "Id", "MsgLine", "Clock", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
